### ISSUE TITLE
Its requiring Passphrase, but I cannot input password

### ISSUE THREAD

**Issue by webcare-live** [jordanbtucker/odrive-crypt#2]
Its requiring Passphrase, but I cannot input password.
I cannot type anything (it doesn't allow me to do that).

Windows 10

![image](https://cloud.githubusercontent.com/assets/14162372/23826789/e933199c-06ac-11e7-9717-157f3e72b949.png)

**Comment by jordanbtucker** [comment]
Even though nothing is displayed when you type a character, it's still accepting the characters. Just type your password and press enter.

This is so that if someone is watching your screen, they will not know the length of your password.

You can use the `--verbose` option to see what files are being decrypted.

**Comment by webcare-live** [comment]
Thanks, its working well. You are superstar!
